# Generated by Django 5.0.6 on 2024-05-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
    ]
