# Generated by Django 5.0.6 on 2024-05-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_marketing',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_marketing_promotional',
            field=models.FloatField(default=0, verbose_name='Price Promo'),
        ),
    ]
